### ISSUE TITLE
Ctrl+Qlt+T does not seem to be a useful key combination

### ISSUE THREAD

**Issue by lvanvugt** [jimmymcp/al-test-runner#12]
Ctrl+Qlt+T does not seem to be a useful key combination as this opens the **Terminal** menu.

BTW: finally I got to start using your extension, James; great work.

**Comment by jimmymcp** [comment]
Hi Luc, glad that you approve 😊

I can't find a default shortcut for Ctrl+Alt+T in VS Code - is that a shortcut that you've created? You can change the shortcuts that are associated with test runner commands by searching for Keyboard Shortcuts in the command palette. 

![image](https://user-images.githubusercontent.com/19267298/74419240-81752400-4e41-11ea-960a-66b615afae26.png)

**Comment by lvanvugt** [comment]
This is what's happening in my VSCode when using Ctrl+Alt+T:

![image](https://user-images.githubusercontent.com/18466198/74425790-8db6ac80-4e54-11ea-9e87-33136d599eba.png)

And yes, of course I can change the shortcuts. Was however wondering if more have the same issue.

**Comment by jimmymcp** [comment]
Strange - the menu ought to open with Alt+T not Ctrl+Alt+T 😕
