### ISSUE TITLE
Code Coverage in Proecedures shows 0%

### ISSUE THREAD

**Issue by IceOnly** [jimmymcp/al-test-runner#120]
I have a Workspace with two apps.
MainApp and TestApp.

I Configured the al test runner like discribed here:
https://github.com/jimmymcp/al-test-runner/issues/45#issuecomment-1222147738

In the Output Window the coverage is calculated:
![image](https://github.com/jimmymcp/al-test-runner/assets/3911556/55d94f80-304b-4c9e-9446-17ce967895a2)

But all procedures in the MainApp and TestApp will show 0% percent, but i know the lines are hit:
![image](https://github.com/jimmymcp/al-test-runner/assets/3911556/b031653a-787f-405f-a15f-9c509a6b29c7)

PS: The references in this case are 0 because its an implentation of an interface :)

**Comment by jimmymcp** [comment]
hi, great that you are using the code coverage 🙂

first thing to check, the code lens stats are only updated each time the whole test suite is run (not individual tests or test codeunits). The code coverage icon in the status bar (bottom right) allows you to toggle the code coverage highlighting between the previous test run and the last time all of the tests were run.

**Comment by IceOnly** [comment]
Perfect! The button in the Status bar was exactly that i missed!
