### ISSUE TITLE
Error: Cannot set properties of undefined

### ISSUE THREAD

**Issue by MaxFalcone** [jimmymcp/al-test-runner#127]
Hi, since last update `v0.10.2` I'm getting an error when trying to switch codecoverage on
![image](https://github.com/jimmymcp/al-test-runner/assets/72614595/eb348769-d281-4801-8b5b-ec15b1705ab7)

Tried to rollback to the previous verion `v0.10.1` then codecoverage works again.

**Comment by jimmymcp** [comment]
Thanks, fix for the release building now...
