### ISSUE TITLE
ERROR DIALOG: One or more errors occurred while closing the page

### ISSUE THREAD

**Issue by nickgoddard777** [jimmymcp/al-test-runner#133]
When running tests on a new project I get the following error. I do not have Performance Toolkit installed on my Container. I set the setting enablePerformanceProfiler to false.

![image](https://github.com/jimmymcp/al-test-runner/assets/332366/3f6cabc5-47f1-4e37-b88f-ac985000a09b)

**Comment by nickgoddard777** [comment]
This actually looks like an issue with the Run-TestsInBcContainer command rather than with the al-test-runner. I have recreated my container with performance profiling turned on and that has got round the error.

**Comment by JeremyVyska** [comment]
Hate to bug, but I'm also running into the issue:
```
ERROR DIALOG: One or more errors occurred while closing the page.

Profiling on session x has already been stopped.
```

What did you change in your docker creation that helped?
