### ISSUE TITLE
[BC24] Downloading Performance Profile or Code Coverage results in a timeout

### ISSUE THREAD

**Issue by someC0d3r** [jimmymcp/al-test-runner#134]
I currently try to use the AL Test Runner, which itself works fine but as I try to make use of the features of downloading the performance profile  or code coverage the script runs unfortunately into a timeout.

PowerShell itself displays me that it wants to download said files but it stops at a "random" byte amount and it doesn't progress anymore. After few minutes an error comes up: "Timeout reached."

Is there maybe some setting I must set on the BC server - like "max. download size" (I don't know; I'm just guessing) or maybe sth. else? Or should I consider some parameter when I create a new BC container?

AL Test Runner version: v10.10.11 (pre-release) & v0.10.3
BcContainerHelper: 6.0.11
BC Version: BC24 (Preview)
Locale Docker container

If you maybe need any further information, let me know! :-)

```
Running tests on bc240-de-prev, company CRONUS DE, tenant default, codeunit 1234567, function SomeTestProcedure, extension Some Extension, test runner 130450, culture en-US
Connecting to http://localhost:80/BC/cs?tenant=default&company=CRONUS%20DE
Codeunit 1234567 SomeTestCodeunit
    Testfunction SomeTestProcedure Success (6.694 seconds)
Downloading code coverage to .//.altestrunner//codecoverage.json
Tenant Throttler: The request timed out while waiting in the requests queue.
```

**Comment by jimmymcp** [comment]
Yes, I've seen the same behaviour as well - but only in BC24 containers. What version of BC are you working against?

**Comment by jimmymcp** [comment]
If you have any time it would be interesting to see if other REST calls work OK with the container or whether they also hang. Maybe this is a BC24 issue?

**Comment by jimmymcp** [comment]
this seems to be a problem using REST in BC24. If I call the same service using SOAP it downloads the performance profile data. Have started implementing this alternative in the ALTestRunner PowerShell module.
