### ISSUE TITLE
Cannot open page 130455. You might need to import the test toolkit to the container

### ISSUE THREAD

**Issue by sirhc101** [jimmymcp/al-test-runner#15]
Hello James,

I really love the altestrunner but for some reason I run into this error for a while and could not figure out what's wrong.
```ps
PS C:\DevOps\MyApp\test> cd "c:\DevOps\MyApp\test"
PS C:\DevOps\MyApp\test> Invoke-ALTestRunner -Tests All -ExtensionId 79081a2a-d3db-4c71-b144-af22b403e2e4 -ExtensionName "My App.Test"
Please select a company to run tests in:
[0]: Cancel
[1]: CRONUS DE
[2]: My Company
1
Running tests on bc, company CRONUS DE, extension My App.Test
Cannot open page 130455. You might need to import the test toolkit to the
container and/or remove the folder
C:\ProgramData\NavContainerHelper\Extensions\bc\PsTestTool-4 and retry. You
might also have URL or Company name wrong.
At C:\ProgramData\NavContainerHelper\Extensions\bc\PsTestTool-4\PsTestFunctions
.ps1:264 char:9
+         throw "Cannot open page $testPage. You might need to import t ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Cannot open pag...any name wr
   ong.:String) [], RuntimeException
    + FullyQualifiedErrorId : Cannot open page 130455. You might need to impor
   t the test toolkit to the container and/or remove the folder C:\ProgramDat
  a\NavContainerHelper\Extensions\bc\PsTestTool-4 and retry. You might also
 have URL or Company name wrong.

Error occurred, retrying...
```

I tried everything to get it to work back again.
- Recreated container (BC15 + BC16)
- Reset Docker to factory defaults
- Imported Test Toolkit again
- Uninstalled NavContainerHelper, Reinstalled newest version

Do you've any advice what I should look for?

Thank you very much
Chris

**Comment by jimmymcp** [comment]
Hi Chris,

Glad that you like the extension 👍

I've only seen that error message when the company name has been wrong in the config file. I'd check that first - does "CRONUS DE" company exist in container "bc"? I assume it must as you are prompted to select the company first. You could double check the company name in the config file (use the _Open Config File_ command to open the json file and check the _Company Name_ value.

Cheers,
James

**Comment by sirhc101** [comment]
Hi James,

thank you for your quick response!
`config.json` looks good:
![image](https://user-images.githubusercontent.com/39621236/79252302-ae65a780-7e81-11ea-9b3d-84fce47bad16.png)

Exactly like in the companies list:
![image](https://user-images.githubusercontent.com/39621236/79252276-a6a60300-7e81-11ea-8312-c825a87d8ce1.png)

**Comment by jimmymcp** [comment]
Have you tried what it says in the error message:

"remove the folder C:\ProgramDat  a\NavContainerHelper\Extensions\bc\PsTestTool-4 and retry"?

Otherwise, it might be a question for Freddy about the navcontainerhelper module.

**Comment by sirhc101** [comment]
Ok, that's weird... now it works again, but what I've done I already did before.

What I did:
1. Remove container
2. Uninstall NavContainerHelper (ALL versions)
3. Factory Reset Docker
4. Install newest NavContainerHelper version (0.6.5.6)
5. Create new container (BC16)

No idea what went wrong or what I did wrong before, but now it works. Thank you for your support!
