### ISSUE TITLE
Issue when running AL Test Runner against a COMSO Alpaca container

### ISSUE THREAD

**Issue by lvanvugt** [jimmymcp/al-test-runner#152]
When executing tests using f.e. `Run All Tests` against a COSMO Alpaca container I am getting the error
```
Error: No such object: fps-alpaca.westeurope.cloudapp.azure.com
Get-CompanyInBCContainer Telemetry Correlation Id: 84636177-165a-4719-a992-8dd723d8054e
The property 'Config' cannot be found on this object. Verify that the property exists.
```
I know that one of the requirements for using AL Test Runner is to have a docker container, so, I guess COSMO Alpaca containers are not set for this.
Would it be a lot of work to get it working against them?

I am also logging this question to the COMSO Alpace team.

**Comment by lvanvugt** [comment]
Yoo, James, thanx for the cooperative repsonse. Yes, I could be able to share an Alpca container with you. Let me first ask inside 4PS how to that.

**Comment by lvanvugt** [comment]
@jimmymcp, see my pm on LinkedIn

**Comment by lvanvugt** [comment]
@jimmymcp could you share your update on this issue also here (as you did in a pm to me)?

**Comment by jimmymcp** [comment]
Hi,

- Install the pre-release of the extension
- Enable a new extension setting "Run Tests via URL"
- Make sure that bccontainerhelper is available on the machine that is running VS Code and is up to date

This solution uses the New-BCCompilerFolder command to create a local folder which includes the necessary dlls to connect to BC and run the tests.

You should be prompted to enter the name of the BC company to run the tests in. (It would be better to retrieve a list of companies from the API but for now this is just free text).

If you want to debug or enable code coverage or performance profile then you will need the Test Runner Service app installed in the container. I couldn't find a way to do this other than cloning https://github.com/jimmymcp/test-runner-service and publishing from VS Code. I wasn't able to upload the extension to the Extension Mgt page or open a terminal to the container in my test. Maybe there is a better way to install from an app file into an Alpaca container - let me know.

Once the Test Runner Service app is installed you should be able to debug and use code coverage and performance profiles.

The extension will suggest the URL for the testRunnerServiceUrl in the config file (use the AL Test Runner: Open Config File command to open it). This suggestion is almost correct. You need to include soap at the end of the server instance, like this:

https://cosmo-alpaca-enterprise.westeurope.cloudapp.azure.com/f027fcee793csoap/WS/CRONUS%20UK%20Ltd./Codeunit/TestRunner?tenant=default

**Comment by lvanvugt** [comment]
@jimmymcp testing it right now.

> * Install the pre-release of the extension
Done. Well, actually it's already a normal release
> * Enable a new extension setting "Run Tests via URL"
Done
> * Make sure that bccontainerhelper is available on the machine that is running VS Code and is up to date
Yep

> You should be prompted to enter the name of the BC company to run the tests in. (It would be better to retrieve a list of companies from the API but for now this is just free text).
This indeed is happening
> The extension will suggest the URL for the testRunnerServiceUrl in the config file (use the AL Test Runner: Open Config File command to open it). This suggestion is almost correct. You need to include soap at the end of the server instance, like this:
It does and have added `soap` as per your suggestion.
But when running a test from the link above the test method I am getting a whole list of errors:
```
Invoke-ALTestRunner -Tests Test -ExtensionId "1f9cf0a8-5e09-4a90-bc37-e393017e92d5" -ExtensionName "4PS 
Base Application Tests W1" -FileName "c:\Users\lvvugt\source\repos\4PS\4PSConstructExtensionsW1\4PS Base Application\test\src\service\TestSMSUPPrdUnitPrice.Codeunit.al" -SelectionStart 11 -LaunchConfig '{"type":"al","request":"launch","name":"launch: ALTestRunner_1068_lvvugt","server":"https://fps-alpaca.westeurope.cloudapp.azure.com","serverInstance":"f0cb8654cd90dev","port":443,"authentication":"UserPassword","environmentType":"OnPrem","tenant":"default","startupObjectType":"Page","startupObjectId":130451,"breakOnError":true,"launchBrowser":true,"enableLongRunningSqlStatements":true,"enableSqlInformationDebugger":true}' -RunViaURL -GetCodeCoverage -GetPerformanceProfile
true}' -RunViaURL -GetCodeCoverage -GetPerformanceProfileRunning tests on fps-alpaca.westeurope.cloudapp.azure.com, company CRONUS Nederland BV, tenant default, codeunit 11130320, function ChangeUnitPriceWhenAllowChangingUnitPriceEqualsFalseAndStatu
sEqualsProposal, extension 4PS Base Application Tests W1, test runner 130450, culture en-US
Copy-Item: C:\Users\lvvugt\.vscode\extensions\jamespearson.al-test-runner-10.14.1\PowerShell\Invoke-RunTestsViaUrl.ps1:94:5
Line |
  94 |      Copy-Item $testDlls -Destination $PsTestToolFolder -Force
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path 'C:\ProgramData\BcContainerHelper\compiler\2f558bf1-f2b7-409c-a77c-ae077e5f9f55\dlls\Test Assemblies' because it does not exist.
Add-Type: C:\Users\lvvugt\AppData\Local\Temp\3721c7f4-160f-484f-b7f6-115e11aef9ea\PsTestFunctions.ps1:10:16
Line |
  10 |  Add-type -Path $clientDllPath
     |                 ~~~~~~~~~~~~~~
     | Cannot bind parameter 'Path' to the target. Exception setting "Path": "Cannot find path
     | 'C:\Users\lvvugt\AppData\Local\Temp\3721c7f4-160f-484f-b7f6-115e11aef9ea\Microsoft.Dynamics.Framework.UI.Client.dll' because it does not exist."
Add-Type: C:\Users\lvvugt\AppData\Local\Temp\3721c7f4-160f-484f-b7f6-115e11aef9ea\PsTestFunctions.ps1:11:16
Line |
  11 |  Add-type -Path $newtonSoftDllPath
     |                 ~~~~~~~~~~~~~~~~~~
     | Cannot bind parameter 'Path' to the target. Exception setting "Path": "Cannot find path 'C:\Users\lvvugt\AppData\Local\Temp\3721c7f4-160f-484f-b7f6-115e11aef9ea\Newtonsoft.Json.dll'    
     | because it does not exist."
ParserError: C:\Users\lvvugt\AppData\Local\Temp\3721c7f4-160f-484f-b7f6-115e11aef9ea\ClientContext.ps1:20:41
Line |
  20 |  … rviceUrl, ([Microsoft.Dynamics.Framework.UI.Client.AuthenticationSche …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Unable to find type [Microsoft.Dynamics.Framework.UI.Client.AuthenticationScheme].
Connecting to https://fps-alpaca.westeurope.cloudapp.azure.com/f0cb8654cd90/cs?tenant=default&company=CRONUS Nederland BV
InvalidOperation: C:\Users\lvvugt\AppData\Local\Temp\3721c7f4-160f-484f-b7f6-115e11aef9ea\PsTestFunctions.ps1:40:26
Line |
  40 |          $clientContext = [ClientContext]::new($serviceUrl, $credentia …
     |                           ~~~~~~~~~~~~~~~
     | Unable to find type [ClientContext].
InvalidOperation: C:\Users\lvvugt\AppData\Local\Temp\3721c7f4-160f-484f-b7f6-115e11aef9ea\PsTestFunctions.ps1:491:9
Line |
 491 |          [ClientContext] $clientContext,
     |          ~~~~~~~~~~~~~~~
     | Unable to find type [ClientContext].
Downloading code coverage to .//.altestrunner//codecoverage.json
A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
ConvertFrom-Csv: C:\Users\lvvugt\.vscode\extensions\jamespearson.al-test-runner-10.14.1\PowerShell\Get-CodeCoverage.ps1:43:41
Line |
  43 |          $CodeCoverage = ConvertFrom-Csv $Result -Header ('ObjectType' …
     |                                          ~~~~~~~
     | Cannot validate argument on parameter 'InputObject'. The argument is null. Provide a valid value for the argument, and then try running the command again.
Downloading performance profile to ./.altestrunner/PerformanceProfile.alcpuprofile
A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
```
Indeed the things that can't be found are not in the referenced directories.

Any hints on what should be done?

**Comment by lvanvugt** [comment]
BTW: when running it the first time a download started from the BC artifacts feed
```
Downloading artifact /sandbox/25.1.25873.27496/w1
```
Is the version unimportant? My container has BC24 in it?

**Comment by jimmymcp** [comment]
Hey Luc,

Please make sure that the bccontainerhelper module is up to date. Looks like it has created a compiler folder without the test dlls. Please delete that folder, ```Update-Module bccontainerhelper```, and try again.

btw: for my purposes, no, I don't think the version of the artifacts that is downloaded is important.

**Comment by jimmymcp** [comment]
@lvanvugt, updating here for visibility.

So, this is working now - don't know if you've done much more testing? I tried to include the Test Runner Service app to be installed automatically into new containers but couldn't get it to work. Maybe that is only supported with Alpaca subscriptions?

**Comment by lvanvugt** [comment]
Yep, working.
To get the Test Runner Service app we will add it to our external app storage which Alpaca can then access. No responsibilty for AL Test Runner.
Closing this issue.

**Comment by lvanvugt** [comment]
And of course, thanx for the help
