### ISSUE TITLE
No tests results stored

### ISSUE THREAD

**Issue by NKarolak** [jimmymcp/al-test-runner#16]
After a long time of AL Test Runner abstinence, I've tried using the extension again, this time for a local, BC 16 targeting workspace consisting of the main app and a test app.

My issue is that "Run test" does not store any results, the folder stays empty:
![image](https://user-images.githubusercontent.com/34504100/81909961-a3f71480-95cb-11ea-80c0-77bb528ece59.png)
Hovering the test functions returns 

> There are no results for this test 🤷‍♀️

The VS Code Terminal has logged that it actually tried to do the right thing:
```
PS MyRepoPath\test> cd "MyRepoPath\test"
PS MyRepoPath\test> Invoke-ALTestRunner -Tests Test -ExtensionId 3c2f6d94-3d73-4f42-8756-ac3c8af4846c -ExtensionName "MyTestAppName" -FileName "MyRepoPath\test\src\Tests\TestAttributes.Codeunit.al" -SelectionStart 12
Running tests on BC-Last-Rel-DE, company CRONUS DE, codeunit 5559711, function NoUDIItemCategoryShownOnItemCategoriesPage, suite MyTestSuiteName
WARNING: TaskScheduler is running in the container. Please specify -EnableTaskScheduler:$false when creating container.
Copy from container BC-Last-Rel-DE (C:\ProgramData\NavContainerHelper\Extensions\BC-Last-Rel-DE\my\8bf264f6-d12f-46b8-a734-5483abbf5b40.xml) to MyRepoPath\test\.altestrunner\8bf264f6-d12f-46b8-a734-5483abbf5b40.xml
```
After that, no error.
However, I've observed the docker container folder during the test run, and an XML file is created there, and then immediately removed. It has not been copied to MyRepoPath\test\\.altestrunner\ as specified by the terminal log.

Any ideas?

**Comment by jimmymcp** [comment]
Hi Natalie,

Were some tests actually run?

The results from that test run are copied to a unique file (named with a guid as per your log) but then split into separate xml files for each test codeunit under the Results folder. The <guid>.xml file is then deleted.

The only reason I can think of for not storing the results is that there weren't any results to store. Did you publish your app before running the tests?

**Comment by NKarolak** [comment]
Apologies, I have to blame myself. There are two conflicting parties :)

My test app is coded in a way that whenever you install it (hence on each publish), a specific Test Suite is deleted, created and filled with all my own test functions. No need to "Get Test Codeunits" manually. 

The AL Test Runner tries to run the test in the very same Test Suite like my test app initialization process = conflict. My app deletes your results right away. 
When I comment out my Test Suite initialization process, your app works as intended.

The actual solution would be to let the AL Test Runner use another Test Suite. Could you provide an optional setting for choosing a specific Test Suite name?

**Comment by jimmymcp** [comment]
Yes, you can open the config.json and supply the test suite name.

Although, there shouldn't be any need for install code to populate a test suite (if you are using BC15 or later)? If you use the AL Test Tool page and paste your extension ID the tests will be discovered from your extension (that's how the PowerShell runner finds and executes the tests).

**Comment by NKarolak** [comment]
Uh, the config.json :-)  I should have found that myself.

I am using BC 16.
What do you mean with "pasting my extension ID" when using the AL Test Tool page? Where and when to paste?

**Comment by jimmymcp** [comment]
Sorry, I meant "Command Line Test Tool" not "AL Test Tool". There is a field on that page you can paste your extension id from app.json into.

![image](https://user-images.githubusercontent.com/19267298/82312832-7f31e100-99bf-11ea-8aa4-c7be6dd89df0.png)
