### ISSUE TITLE
Error: Cod75650.UnblockDeletionEnabledFLX.al is not an AL test codeunit

### ISSUE THREAD

**Issue by lvanvugt** [jimmymcp/al-test-runner#17]
Wanting demo the AL Test Runner tried to run the first test in the testcodeunt Cod75650.UnblockDeletionEnabledFLX.al and got the error:

`Cod75650.UnblockDeletionEnabledFLX.al is not an AL test codeunit`

Find attached the test codeunit itself, that was created using our ATDD.TestScriptor.

[Cod75650.UnblockDeletionEnabledFLX.al.txt](https://github.com/jimmymcp/al-test-runner/files/4730034/Cod75650.UnblockDeletionEnabledFLX.al.txt)

What kind of assumption is AL Test Runner making about a test codeunit, apart from the **Subtype** property set to _Test_?

**Comment by jimmymcp** [comment]
Looks like this is due to a case sensitive search for Subtype = Test. The sample file has SubType = Test. I'll change it be case insensitive. Thanks Luc.

**Comment by jimmymcp** [comment]
Fixed in v0.3.3

**Comment by lvanvugt** [comment]
Verified on v0.3.3 and OK.
