### ISSUE TITLE
Unexpected token } in JSON at position

### ISSUE THREAD

**Issue by aptMattKoe** [jimmymcp/al-test-runner#21]
Hi :)

I've get the error "Unexpected token } in JSON at position" everytime I want to start the tests:
![image](https://user-images.githubusercontent.com/57363453/85856690-bcf10900-b7b8-11ea-8dd7-2b426d92c2fe.png)

After some hours I had found the error. In the launch.json was a comma at the end. Sure an error but I've searched the wrong places. 
![image](https://user-images.githubusercontent.com/57363453/85856897-19542880-b7b9-11ea-9339-bdf48d6462d8.png)

Is that an error of AL Test Runner?

**Comment by jimmymcp** [comment]
Hi,

Yes and no. AL Test Runner could be more robust at handling invalid JSON - you've probably noticed that having a trailing comma or part of the file commented out doesn't stop you from publishing an app. I had a quick look the other night and could use the VS Code API to read the launch configurations, which gets past this error.

However, PowerShell just throws the same error then (ConvertFrom-Json fails to read launch.json if its contents aren't valid JSON).

It would be nice to tighten this up at some point, but for now launch.json has to be valid JSON for the extension to be able to read it.

**Comment by jimmymcp** [comment]
This is handled better in v0.4.0. Your specific case of having a trailing comma would still cause a problem, but you can have line or block comments in launch.json now.

**Comment by aptMattKoe** [comment]
Thanks for the info (Its something :)) and the tool! :) Used it several times 3 hours ago! :)
