### ISSUE TITLE
CompanyName is NULL

### ISSUE THREAD

**Issue by lksg** [jimmymcp/al-test-runner#22]
Hi Jimmy,

I currently can't use the Tool because I get the following Error:

```
Invoke-RunTests : Das Argument kann nicht an den Parameter "CompanyName" gebunden werden, da es NULL ist.
.vscode\extensions\jamespearson.al-test-runner-0.4.0\PowerShell\Invoke-ALTestRunner.ps1:82 Zeichen:21
+     Invoke-RunTests @Params
+                     ~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-RunTests], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Invoke-RunTests
```

I tried including the tenant in my launch json after I saw that multi tenancy was added in a PR but nothing  changed.

Regards Leon

**Comment by jimmymcp** [comment]
Please check the AL Test Runner config file (you can use the _Open Config File_ action in VS Code). The BC company to run the tests in should be set there - I assume that it isn't?

If this isn't set in the config file one of two things ought to happen:
1. If there is only one company in the container then that company name is filled in automatically
2. If there are multiple companies you will be prompted in the PowerShell terminal to make a selection

Cheers,
James
