### ISSUE TITLE
Error when using 'Debug Test' Cannot bind argument to parameter 'InputObject' because it is null.

### ISSUE THREAD

**Issue by mhenricus** [jimmymcp/al-test-runner#27]
Probably I have wrong setting, but which one. I get the error "Cannot bind argument to parameter 'InputObject' because it is null." in the terminal of VS Code when using 'Debug Test'.
I have added this setting to the config.json: 
    "testRunnerServiceUrl":  "http://latest17-base-t-1022:7047/BC/WS/CRONUS%20International%20Ltd./Codeunit/TestRunner_RunTest?tenant=default",
And this is my launch.json

{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Attach: Your own server",
            "type": "al",
            "request": "attach",
            "server": "http://latest17-base-t-1022",
            "serverInstance": "BC",
            "tenant": "default",
            "authentication": "UserPassword",
            "breakOnError": true,
            "breakOnRecordWrite": false,
            "enableSqlInformationDebugger": true,
            "enableLongRunningSqlStatements": true,
            "longRunningSqlStatementsThreshold": 500,
            "numberOfSqlStatements": 10,
            "breakOnNext": "WebServiceClient"
        }
    ]
}

BTW. Codeunit 79150 does not get a OData URL in the Web Services, only a SOAP URL.

**Comment by jimmymcp** [comment]
Hi,

Codeunits do get a REST endpoint, even though it isn't listed in the web services page. The url should be something like this:

http://latest17-base-t-1022:7048/BC/ODataV4/TestRunner_RunTest?company=CRONUS%20International%20Ltd.
