### ISSUE TITLE
Commented test functions are decorated

### ISSUE THREAD

**Issue by pzentner** [jimmymcp/al-test-runner#3]
Test functions that are commented out are still decorated with "missing tests". Not a big issue, but I figured, I'll let you know.

Repo:

Create a function in a test codeunit as follows:

```
/*
[Test]
procedure MyTest()
begin
end;
*/

```

**Comment by jimmymcp** [comment]
Thanks, will fix sometime 👍

**Comment by jimmymcp** [comment]
Fixed in 0.1.11
