### ISSUE TITLE
Test cases Code Coverage portion not showing any results

### ISSUE THREAD

**Issue by srkkoneti** [jimmymcp/al-test-runner#34]
Hi,

I ran the ALTestRunner App, for few of my test cases, I am getting execution results in Results folder as an xml file. 

But, I not getting any code review portion of results, to verify which code executed. Please find the attached screen.

Let me know, if i miss any steps.

![image](https://user-images.githubusercontent.com/39953344/112982061-a6c60e00-9179-11eb-9b18-a481c8ab9223.png)

**setting.Json**
![image](https://user-images.githubusercontent.com/39953344/112983576-7d0de680-917b-11eb-9f08-bdb643913d22.png)

**config.json**
{
    "containerResultPath":  "C:\\ProgramData\\BcContainerHelper\\Extensions\\test\\my",
    "launchConfigName":  "test",
    "securePassword":  "01000000d08c9ddf0115d1118c7a00c04fc297eb01000000052feaf62e6a3e4ca7bf7574b93374370000000002000000000003660000c00000001000000056db47761b135d9356c8b9c4c458153e0000000004800000a000000010000000c8d8423ad4d5788ce96133722cb5b7d908000000a72e63acf3b509bf14000000c9ac2c5b4a64b6d3aa8524f0b582ff2e20591d5c",
    "userName":  "dev",
    "companyName":  "CRONUS USA, Inc.",
    "testSuiteName":  "",
    "vmUserName":  "",
    "vmSecurePassword":  "",
    "remoteContainerName":  "",
    "dockerHost":  "",
    "newPSSessionOptions":  "",
    "testRunnerServiceUrl":  "http://test:7048/BC/ODataV4/TestRunner?company=My%20Company\u0026tenant=default",
    "codeCoveragePath":  "./test/.altestrunner//codecoverage.json"
}

**Comment by jimmymcp** [comment]
Hi, is the codecoverage.json file being created? I'm guessing not, you need to have double slashes in the codeCoveragePath i.e. .//test//.altestrunner//codecoverage.json This specifies the path that the code coverage result will be saved to relative to the root of your test folder.

There is also a VS Code setting for the code coverage path. This should be the path of the code coverage file relative to your production code. Both settings need to be set.

![image](https://user-images.githubusercontent.com/19267298/112993400-14b20b80-9161-11eb-9611-5c399d5d637f.png)

In my case I have the following structure:

- app
  - src
    - (production source code)
- tests
  - .altestrunner
    - codecoverage.json
  - src
    - (test code)

codeCoveragePath in config.json is set to ".//.altestrunner//codecoverage.json"
Code coverage path in VS Code settings is set to ../tests/.altestrunner/codecoverage.json (again, use double slashes if you are editing the settings.json file directly)
