### ISSUE TITLE
Unable to debug test procedures "Resource not found..."

### ISSUE THREAD

**Issue by horribleCodes** [jimmymcp/al-test-runner#38]
I can run tests just fine, but when I try to debug one, I always get the following error code in the terminal:

```Resource not found for the segment 'TestRunner_RunTest'.  CorrelationId:  0f8e08b4-b769-4314-a577-ecda5ab1bd3a.```

Note that the `CorrelationId` will be different every time. Additionally, an error notification from VS Code appears, which just says:

```Running the contributed command: 'altestrunner.debugTest' failed.```

Here is my `config.json` file:
```json
{
    "containerResultPath":  "C:\\ProgramData\\BcContainerHelper",
    "launchConfigName":  "Debug Test",
    "securePassword":  "XXXXXX",
    "userName":  "XXXXX",
    "companyName":  "CRONUS AG",
    "testSuiteName":  "",
    "vmUserName":  "",
    "vmSecurePassword":  "",
    "remoteContainerName":  "",
    "dockerHost":  "",
    "newPSSessionOptions":  "",
    "testRunnerServiceUrl":  "http://ll-bc-at:7048/BC/ODataV4/TestRunner?company=CRONUS%20AG",
    "codeCoveragePath":  ".//.altestrunner//codecoverage.json"
}
```

And my `launch.json` file:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Test App",
            "request": "launch",
            "type": "al",
            "environmentType": "OnPrem",
            "server": "http://ll-bc-at",
            "serverInstance": "BC",
            "authentication": "Windows",
            "startupObjectId": 130401,
            "startupObjectType": "Page",
            "breakOnError": true,
            "launchBrowser": true,
            "enableLongRunningSqlStatements": true,
            "enableSqlInformationDebugger": true,
            "tenant": "default",
            "schemaUpdateMode": "ForceSync"
        },{
            "name": "Debug Test",
            "type": "al",
            "request": "snapshotInitialize",
            "environmentType": "OnPrem",
            "server": "http://ll-bc-at",
            "serverInstance": "BC",
            "authentication": "Windows",
            "tenant": "default",
            "breakOnNext": "WebClient"
        }
    ]
}
```

I find it a bit odd that I'd have to enter my credentials even though the authentication method is set to `Windows`, but if I leave the properties `securePassword` and `userName` blank I will always get prompted to enter them when trying to debug.

**Comment by jimmymcp** [comment]
Do you have the Test Runner Service extension installed in the container? If not, you will need that. Also, the testRunnerServiceUrl key of the config.json file should have the OData endpoint that the test runner service can be reached on (hover over the key name for an example of what the url should look like).

You can installed the extension with the "Install Test Runner Service" command if the container is running locally or you can download it manually from here: https://github.com/jimmymcp/test-runner-service/raw/master/James%20Pearson_Test%20Runner%20Service.app

The test runner works best with NavUserPassword authentication, you might run into some problems with Windows authentication. I haven't tested much with Windows auth as I never use it. Let me know how you get on.

**Comment by marknitek** [comment]
I had a situation, where the test runner was installed but the webservice was not published... BC26
I'll leave that here for reference
