### ISSUE TITLE
'altestrunner.installTestRunnerService' not found

### ISSUE THREAD

**Issue by lvanvugt** [jimmymcp/al-test-runner#39]
Hey James,

Finally I wanted to get going with the code coverage part of your tool as I wanted to mention, and add a short demo, to the 2nd edition of my book.
Your blog post [https://jpearson.blog/2021/02/07/measuring-code-coverage-in-business-central-with-al-test-runner/](https://jpearson.blog/2021/02/07/measuring-code-coverage-in-business-central-with-al-test-runner/) looked very comprehensive, but apparently some things are missing here (and nothing mentioned about this in the documentation in the VS Code extension).

As per step 1 one of the Setup described in the blog post I wanted to install the Test Runner Service app with the command in Visual Studio Code. First time I did this I got an error that resembles the error reported here #36. Unfortunately I could not reproduce as I did restart VS Code - hoping this might solve it. When restarted and triggering the same command I did get another error:

```
Command 'AL Test Runner: Install Test Runner Service' resulted in an error (command 'altestrunner.installTestRunnerService' not found)
```

The step also mentions _If it is already installed you will need to uninstall and unpublish the existing version first_. How do you do that?

So, at this point I am stuck, which is somewhat unfortunate as I had hoped to finish this part of my book today. Nevertheless, would be very pleased if you can help me out asap. Maybe get online together to solve this.

**Comment by jimmymcp** [comment]
Hi Luc,

That's strange - the command ought to be write some commands into the al test runner terminal. Do you get any output/errors in that terminal?

Otherwise is there anything related to al test runner in the Log (Extension Host) view of the output pane?

You can either uninstall apps from the Extension Management page in the web client or with the Uninstall-BcContainerApp function in bccontainerhelper.

**Comment by lvanvugt** [comment]
Hey, Jamew. Will investigate. What app to uninstall?

**Comment by jimmymcp** [comment]
This is only necessary if you have a previous version of the "Test Runner Service" app installed and you want to install a later version.

At the moment the command only supports installing the test runner service app if it isn't already installed, and not upgrading it if it is already installed. I've got that on my to-do list but for now you'd need to handle that manually with the bccontainerhelper commands.
