### ISSUE TITLE
Test Codecoverage shows 0% 

### ISSUE THREAD

**Issue by StefanMaron** [jimmymcp/al-test-runner#45]
I configured the code coverage like you described in your blog but the overview of codecoverage always says that 0% were hit. 

![image](https://user-images.githubusercontent.com/24838311/129686340-abdaa6f2-dde3-46cc-bd1a-4e8ccfcc7220.png)

Although in the generated codecoverage.json file there are hit lines.
![image](https://user-images.githubusercontent.com/24838311/129686574-2f705b37-2791-4975-9c98-ff460b42b0f0.png)
![image](https://user-images.githubusercontent.com/24838311/129686591-69a7462c-8683-4bc4-b17f-a3d990751c87.png)

I also tried "Toggle Code Coverage" but it does not show anything.

----

![image](https://user-images.githubusercontent.com/24838311/129686739-a6ff2636-9ea1-47a4-98a7-c3d3993888a1.png)
Workspace:
![image](https://user-images.githubusercontent.com/24838311/129686859-e0ac598b-b876-4003-a942-32055dcacc4c.png)
User Settings:
![image](https://user-images.githubusercontent.com/24838311/129686913-17a335e1-f90f-445a-9248-de3639678e8c.png)

![image](https://user-images.githubusercontent.com/24838311/129687117-34395bb9-e0ef-48c1-88e0-457fc7d62b4a.png)

![image](https://user-images.githubusercontent.com/24838311/129692026-e76e0491-573a-4e36-9afd-c86fff2d2881.png)

**Comment by jimmymcp** [comment]
Try removing the codeCoverageExcludeFiles setting. This is a regex. Any objects which have a path that is matched by that regex will be excluded from the code coverage. It looks like all of your source files sit under a folder called test, so I would think they are all being excluded by that setting.

The purpose of that setting is to exclude the test files themselves from being included in the stats (normally you care about code coverage of the production code, not the test code).

**Comment by StefanMaron** [comment]
Removed the setting, but still the same behavior

**Comment by IceOnly** [comment]
@StefanMaron I had the same problem yesterday.

Try the following (adapted for your folder structure):
![image](https://user-images.githubusercontent.com/3911556/146744157-0b0f49d8-494f-4c3c-abdc-b29151ab71d5.png)

**Comment by JohnnyUndercover** [comment]
i struggled with this too, so i want to share what i did to get it running:
My Project is split into MainApp and TestApp.
In my VSCode User Settings i added the following:
![image](https://user-images.githubusercontent.com/30835996/185894972-14289ef2-b269-4ffd-ad55-d477cca36a2e.png)

My AL Test Runner config looks like this (TestApp/.altestrunner/config.json)
![image](https://user-images.githubusercontent.com/30835996/185895760-b88406d6-417c-4172-a801-7ab24ea0c41c.png)

In addition you need to make sure that the Odata Service is up and running on your docker. The Service will be added when you install the Test Runner Service App to your container from the vs code command.
![image](https://user-images.githubusercontent.com/30835996/185896245-2076d855-a2e9-4db1-966b-54794982eae3.png)
Make sure the installation is successfull, by checking if the service was added to your web services:
![image](https://user-images.githubusercontent.com/30835996/185897412-ecdf1f4a-ca92-47f5-aa5d-85dea13b8516.png)

**Comment by StefanMaron** [comment]
Thanks! Using the correct settings helps a lot :D
