### ISSUE TITLE
Get-ServerFromLaunchJson does not work with explicit port

### ISSUE THREAD

**Issue by zabcik** [jimmymcp/al-test-runner#46]
When server uses explicit port (i.e. 23171), then the port is considered as a part of server name (docker container name).
That is wrong. 
Server name (docker container name) is only "MYSB", see the sample bellow.

{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "al",
      "request": "launch",
      "name": "MYSB",
      "server": "http://MYSB:23171/",
      "serverInstance": "BC",
      "authentication": "UserPassword",
      "breakOnError": true,
      "launchBrowser": false,
      "enableLongRunningSqlStatements": true,
      "enableSqlInformationDebugger": true,
      "schemaUpdateMode": "ForceSync",
      "port": 23771
    }
  ]
}

**Comment by jimmymcp** [comment]
Should be an easy fix, I'll try to do that soon. Out of interest, why do you need to specify a port in the server name?

**Comment by jimmymcp** [comment]
v0.6.1
