### ISSUE TITLE
Tests do not start

### ISSUE THREAD

**Issue by FSchneiderYav** [jimmymcp/al-test-runner#48]
Hello,
I have a new repo with test codeunits, If I starte one or some tests, only the icon for Running tests.. in the task bar is running.
![image](https://user-images.githubusercontent.com/47736215/134119425-2f37dee5-5b4a-489b-ba14-793cd1c196d1.png)
The terminal shows no statements to start like Import-Module or Invoke-ALTestRunner.
If I starte tests manually with the commands, the Testing explorer shows nothing
![image](https://user-images.githubusercontent.com/47736215/134119986-498c7243-7ba1-46b9-a630-5938f0c8a035.png)
![image](https://user-images.githubusercontent.com/47736215/134120040-8479bf52-d313-487a-9393-f3b4825d6468.png)

**Comment by jimmymcp** [comment]
It is possible to start a test run but it not finish e.g. if the app fails to compile or fails to publish into the container. In these cases VS Code will continue to display that the tests are running until you finish them manually (at the top of the Test Explorer view). I'd like to improve this but there is no output from the compile or publish commands to know whether they ran successfully or not.

For not, just stop the test run manually, fix any issues that prevented the test from running and run again.

**Comment by FSchneiderYav** [comment]
The app is compiled and published.
I have also stoped the tests in the Test Explorer. When I start a test, two notifications are showen
![image](https://user-images.githubusercontent.com/47736215/134134996-37abc0a9-2a2e-43e7-8399-bd5ee7309bc8.png)
The Test Output shows nothing until I stop the test in the Test Explorer 
![image](https://user-images.githubusercontent.com/47736215/134134902-2ae226c4-c819-4018-9b60-6b8c05b3d955.png)

**Comment by FSchneiderYav** [comment]
I have tried to start single test, single Codeunit and all tests from the Test Explorer, but nothing works. Also to start a single test or a single Codeunit with the Run Test code lens on the single Test/Codeunit is not working.
And I have always an active editor to a test Codeunit

**Comment by jimmymcp** [comment]
OK, what does happen?

Is the al-test-runner terminal created? If so, any output or errors in the terminal? Anything logged in the al-test-runner output window? Does it attempt to compile and publish your test app (assuming that you've got the setting to publish the app before running the tests). Does that succeed?

Is anything related to al test runner logged in the Extension Host log?

**Comment by FSchneiderYav** [comment]
When I starte the tests with the Test Explorer or the code lens button. Only the symbol Running tests in the Task Bar is shown
![image](https://user-images.githubusercontent.com/47736215/134335222-14b0cfef-5203-4040-b088-2ffc2a75fdb6.png)
A al-test-runner terminal is not created and the log in the output window is empty
In the Extension Host log is this entry
![image](https://user-images.githubusercontent.com/47736215/134335783-96a0bfd8-e5e5-48c7-87c2-fb007f817ab2.png)

**Comment by FSchneiderYav** [comment]
@jimmymcp is there anything new about this bug?

**Comment by FSchneiderYav** [comment]
Hello, there is a launchConfigName.
I can only start the tests with the powershell comand invoke-ALTestRunner. But the button in the sidebar or in the test creates no powershell comand

**Comment by jimmymcp** [comment]
Please can you check that launch.json, app.json and .altestrunner/config.json are all valid JSON files e.g. no trailing commas?

VS code is more tolerant of JSON formatting problems than PowerShell. The PowerShell module should be able to cope with comments in those json files, but if you have comments (line or block) in those files you could try removing those as well.

**Comment by BMI-Mike** [comment]
I'm running into the same issue.  One item I noticed is that the TestRunner app is only publishing a WS url, OData is missing.  Within my container, this is what I see after using "Install Test Runner Service":
<img width="1893" alt="image" src="https://user-images.githubusercontent.com/35507227/185816798-f14f1496-39ad-49ea-b041-c2c0aa29bf6e.png">

**Comment by jimmymcp** [comment]
I'm struggling to repro this, so I've added some (optional) debug logging. Please install the latest pre-release version (10.7.17) and turn on the sending to send debug telemetry. This will log some of the function calls and I'll try to figure out what is going on.

![image](https://user-images.githubusercontent.com/19267298/185892514-47e88df6-cace-4d57-925f-c7e5efa894c9.png)

**Comment by FSchneiderYav** [comment]
Hello, I have updated the extension to 10.7.17 and activated "Send Debug Telemetry" and startet the test.

**Comment by jimmymcp** [comment]
Thanks, please update to 10.7.18 and try again.

**Comment by FSchneiderYav** [comment]
I tried, but it didn't work.

**Comment by BMI-Mike** [comment]
I believe I am having the same issue as @FSchneiderYav.  Same symptoms and conditions.  I installed the pre-release version (10.7.18) and enabled the option to Send Debug Telemetry.

**Comment by JavierFuentes** [comment]
Exactly the same problem here!
Al-Test-Runner extension doesn't do anything when I run my Tests...

However, I can run all my Tests using Freddy's `Run-TestsInBCContainer` command using `-extensionId` parameter as described here:  
https://freddysblog.com/2019/10/22/running-tests-in-containers-2/

I wonder if this extension could make use of those same commands that do seem to work without too many requirements in a more comfortable and friendly way...

**Comment by jimmymcp** [comment]
@JavierFuentes the extension does use the commands in the bccontainerhelper function 👍

Before the terminal is created and the PowerShell command the extension reads all of the al files in the workspace and the objects that they contain (so that they can be matched with code coverage and build a test coverage map). I think this is failing.

There is a new command in the new pre-release version (10.7.22), List AL Files. This command will attempt to read all of the al files and list them in a new editor. Please try to run that command and let me know the result. Specifically if there are any error messages, any files whose objects are "undefined" and how long it took to create (the start time and end time are printed at the end of the list).

**Comment by FSchneiderYav** [comment]
```
path                                                                                            | type          | id      | name                                                   
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
c:\Development\Repos\Tests\PagExt_ItemTrkgLines.al  | pageextension | 51350 | Test Item Trkg. Lines extends Item Tracking Lines
c:\Development\Repos\Tests\Cod_TrafficLight.al      | codeunit      | 51350 | Test Traffic Light                               
c:\Development\Repos\Tests\Cod_Permissions.al       | codeunit      | 51356 | Test Permissions                                 
c:\Development\Repos\Tests\Cod_ManSub.al            | codeunit      | 51360 | Test Man. Sub                                    
c:\Development\Repos\Tests\Cod_ItemTrackingFcts.al  | codeunit      | 51359 | Test Item Tracking Fcts.                         
c:\Development\Repos\Tests\Cod_ItemFeatureFilter.al | codeunit      | 51354 | Test ItemFeature Filter                          
c:\Development\Repos\Tests\Cod_InventorySummary.al  | codeunit      | 51351 | Test Inventory Summary                           
c:\Development\Repos\Tests\Cod_InitBaseApp.al       | codeunit      | 51352 | Test Init Base App                               
c:\Development\Repos\Tests\Cod_Feature.al           | codeunit      | 51353 | Test Feature                                     
c:\Development\Repos\Tests\Cod_ExtTextPurchase.al   | codeunit      | 51358 | Test Ext. Text - Purch.                          
c:\Development\Repos\Tests\Cod_ExtendedTextSales.al | codeunit      | 51357 | Test Ext. Text - Sales                           
c:\Development\Repos\Tests\Cod_CorporateDesign.al   | codeunit      | 51355 | Test Corporate Design                            
Started at: 14:45:08 GMT+0200 (Mitteleuropäische Sommerzeit)
Ended at  : 14:45:08 GMT+0200 (Mitteleuropäische Sommerzeit)
```

**Comment by BMI-Mike** [comment]
I'm checking in to see if there has been any progress on this issue.  I'd like to use this extension.

**Comment by jimmymcp** [comment]
It might be useful to see your screen, I'm running out of ideas. I'm on holiday next week, but maybe we can arrange a quick call sometime the week after?
