### ISSUE TITLE
Suggestion: "Publish and Run Current Test"

### ISSUE THREAD

**Issue by NKarolak** [jimmymcp/al-test-runner#5]
When I am modifying a test function and I now want to test the new result, I easily forget that "Run Current Test" won't give me the correct result, since my code changes are not uploaded to the database yet.

Wouldn't it make sense to provide something like "Publish and Run Current Test"?

**Comment by jimmymcp** [comment]
Thanks for the suggestion. This is supported in 0.1.15 - a new "publish before test" setting allows to select whether to call the publish or rapid application publish command before running the tests.
