### ISSUE TITLE
Running API tests is not possible

### ISSUE THREAD

**Issue by lvanvugt** [jimmymcp/al-test-runner#50]
When running API tests (like standard tests for the _Exclude_APIV1_ and _Exclude_APIV2_ extensions) the environment needs to be accessed using Windows authentication and should not have any user related data in the database. See also this discussion
https://www.yammer.com/dynamicsnavdev/threads/1383604008484864.

Now, AL Test Runner forces the creation of a user in the database in the docker container. Thus, I cannot run my API tests using AL Test Runner. Could this be fixed?

**Comment by jimmymcp** [comment]
Hi Luc, sorry I haven't investigated this yet because I never use Windows auth in my containers. I _think_ it just requires the ALTestRunner PowerShell to not pass any credentials to the Run-TestsInBCContainer function in bccontainerhelper.

**Comment by lvanvugt** [comment]
Might be true, but surely, as mentioned there "should not have any user related data in the database" and as "AL Test Runner forces the creation of a user" this is an issue.

**Comment by jimmymcp** [comment]
Strictly, AL Test Runner doesn't create a user in the container. It does prompt you to enter credentials, expecting that you are using NavUserPassword authentication in the container. I can probably check the authentication that is being used in the container before prompting you to enter credentials. But probably not this week.

**Comment by lvanvugt** [comment]
No problem.

BTW: I guess you are right that "AL Test Runner doesn't create a user in the container". But I am quite sure that last week I saw a line in the AL Test Runner log on creating a user.
