### ISSUE TITLE
testRunnerServiceURL tooltip

### ISSUE THREAD

**Issue by fvet** [jimmymcp/al-test-runner#53]
Reading your blog, it seems like the testRunnerServiceURL needs to target the ODATAv4 `TestRunner_RunTest `endpoint. Which is the valid endpoint I suppose.

The tooltip of testRunnerServiceURL suggest (an old value?) ODatav4 `TestRunner `endpoint instead. Maybe update to reflect the new endpoint?

![image](https://user-images.githubusercontent.com/25268332/143033734-dd7595e4-1737-4417-b4a9-d5f2342198be.png)

**Comment by jimmymcp** [comment]
Thanks, the URL has changed since the blog post. That's because the test runner web service has other methods - apart from RunTest - which are used now. The URL is constructed in the PowerShell functions depending on which method is being called. I'll update the blog post.
