### ISSUE TITLE
Feature request: add Filename and SelectionStart as parameters to VS Code commands

### ISSUE THREAD

**Issue by martonsagi** [jimmymcp/al-test-runner#6]
Hi,

Love this extension so far, I'd like to integrate the runner parts into AL Object Designer.

Could you add these optional parameters to below commands?

* filename: `altestrunner.runTestsCodeunit`, `altestrunner.runTest`
* selectionStart: `altestrunner.runTest`

So I'd be able to initiate the test runner like this: 
```
vscode.commands.executeCommand('altestrunner.runTest', fileName, selectionStart);
```

My idea is to list available tests and run them using the context menu.
![image](https://user-images.githubusercontent.com/18100709/69804656-5afb0180-11df-11ea-95b0-42aba4bdc55a.png)

Thanks,
Marton

**Comment by jimmymcp** [comment]
Glad that you like it, thanks for the suggestion.

I've added the parameters in 0.1.11 - looking forward to seeing what you can do with them 👍

**Comment by martonsagi** [comment]
Thank you! I'll give you an update soon. :)
