### ISSUE TITLE
invoke-ALTestRunner

### ISSUE THREAD

**Issue by FrankAuwers** [jimmymcp/al-test-runner#64]
'Invoke-ALTestRunner' is not recognized as an internal or external command

What mus I do for getting this to work?

**Comment by jimmymcp** [comment]
Can you give me some more info? What are you doing when you get this error?

Invoke-ALTestRunner is a function in the ALTestRunner module. When you run a test a new terminal called al-test-runner should be created and the module imported like this. Are there any errors in the al-test-runner terminal?

![image](https://user-images.githubusercontent.com/19267298/168265286-b6bc1c86-24d3-4177-9c0a-4be0cc15396f.png)

**Comment by FrankAuwers** [comment]
![image](https://user-images.githubusercontent.com/37549404/168533420-e1fde42e-638e-4c54-94ef-b56f1229049b.png)

**Comment by jimmymcp** [comment]
Is that a PowerShell terminal? The extension requires that PowerShell is opened by default. If not, see here https://code.visualstudio.com/docs/editor/integrated-terminal#_terminal-profiles for more info about setting it.
