### ISSUE TITLE
Coverage percent shows over a deactivated procedure

### ISSUE THREAD

**Issue by JavierFuentes** [jimmymcp/al-test-runner#68]
Coverage percent shows over a deactivated procedure

![image](https://user-images.githubusercontent.com/5801847/185371098-3ef90d0c-3f22-404e-ab91-1465e0fd8a23.png)

![image](https://user-images.githubusercontent.com/5801847/185371440-4f23cb47-b063-4abf-94bd-f5dab490c855.png)

**Comment by jimmymcp** [comment]
Fix coming in v0.7.12 / v10.7.20
