### ISSUE TITLE
Workspace / multiple app handling 

### ISSUE THREAD

**Issue by sirhc101** [jimmymcp/al-test-runner#7]
Hi,

First of all, I really like the approach of creating an inside-vscode test runner! Great job!!!

Unfortunately I ran into a problem when using developing multiple apps in a vscode workspace. It seems like al-test-runner does not recognize that I switched the folder. The commands always try to start the previous app folder I tested against.
When I kill the terminal session the new session is at the right folder. Additionally it seems that the result display also doesn't work with multiple folders.

If you need additional information pls let me know...

/ chris

**Comment by jimmymcp** [comment]
Hi Chris,

This should be fixed in 0.1.12

Cheers
