### ISSUE TITLE
Add 'culture' to config

### ISSUE THREAD

**Issue by mitrov** [jimmymcp/al-test-runner#70]
Hi James,

We write our tests using the culture 'de-CH' (Switzerland) and our tests currently fail because date format is in en-US (mm/dd/yy).

It would be great if we could specify the culture in the config.

The BCContainerHelper has this parameter: 
https://github.com/microsoft/navcontainerhelper/blob/1e0d93a9fa7bd303d7342cbc04db52089f7fb263/AppHandling/Run-TestsInNavContainer.ps1#L53

Cheers
Džoka

**Comment by jimmymcp** [comment]
Closed in v0.7.13 / v10.7.21
