### ISSUE TITLE
extension gives error when used with vscode open source builds.

### ISSUE THREAD

**Issue by ambujsahu81** [jimmymcp/al-test-runner#74]
**Error Message** : -  Unknown language in `contributes.al-test-runner.language`. Provided value: al

Steps to reproduce : -

-  Clone and build vscode locally.
- Download the extension from [Download Extension](https://marketplace.visualstudio.com/items?itemName=jamespearson.al-test-runner)

![Screenshot](https://user-images.githubusercontent.com/118078892/210101504-1789fa92-b28a-4e15-9a2f-1d76ac83682a.png)

**Comment by jimmymcp** [comment]
The extension depends on the [AL Language](https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al) extension from Microsoft.

**Comment by ambujsahu81** [comment]
@jimmymcp  thanks for reply 🙂 . I will  install [AL Language](https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al) separately in vscode builds.
