### ISSUE TITLE
Authentication to Container with AAD fails

### ISSUE THREAD

**Issue by CPSTOS** [jimmymcp/al-test-runner#76]
Hi Jimmy,

I'm trying to get al-test-runner working with my local Container and AAD authentication. If I got that right, I have to enter my AAD Username and an accesstoken as Username/Password for the al-test-runner credentials. Unfortunately that always ends up with "ERROR DIALOG: You do not have access to Dynamics 365 Business Central. Verify that you have been set up as a valid user in Dynamics 365 Business Central.".

Have you got a hint for me, how to correctly generate that token?
I did try several approaches, with no luck yet.
BCContainerHelpers New-BcAuthContext  looks good and Run-TestsInBcContainer -containerName 'bc-dev-aad' -bcAuthContext $authContext does work without an error, but that AccessToken does not seem to work with al-test-runner either.

Can you spot any wrong track I'm on, without going to much into details? thanks!

Forgot to mention MFA, which is also in the game…

**Comment by jimmymcp** [comment]
Hi,

Sorry, I've never supported AAD authentication, because I never use it in a dev container myself. You need to use NavUserPassword auth instead. I'll leave this issue open as a reminder of a feature request, but I won't be adding it any time soon I'm afraid - unless someone else want to fork and create a PR :-)

**Comment by CPSTOS** [comment]
Hi,

I created a pull request. 
To use AAD Authentication New-BcAuthContext is being used, when a Refresh Token is supplied. The token can be acquired by:
$authContext = New-BcAuthContext -scopes '[your AAD App Id]/user_impersonation offline_access' -tenantID '[your Tenant Id]' -includeDeviceLogin
$authContext.RefreshToken

Best regards

Sven

**Comment by jimmymcp** [comment]
Hi Sven,

That's great thanks. I've merged into the pre-release branch and created v10.7.31. I normally have the pre-release version installed myself and use it for a day or two before merging new changes into the master branch as an extra test that nothing is broken.

Cheers,
James
