### ISSUE TITLE
Support code-workspace (launch configuration)

### ISSUE THREAD

**Issue by christianbraeunlich** [jimmymcp/al-test-runner#79]
Hi,
would it be possible to support the launch section in the code-workspace file without having a .vscode/launch.json file: https://yzhums.com/32067/

I have a code-workspace file with multiple projects and I'm only using the launch configuration in the code-workspace file.

![image](https://user-images.githubusercontent.com/25108568/213427087-dcaf2557-9356-4731-9dc4-1a9451db84c5.png)

Thanks in advance

**Comment by jimmymcp** [comment]
Please install the pre-release 10.7.34 and let me know if this works for you now.
