### ISSUE TITLE
Code coverage % is shown for non-test codeunits

### ISSUE THREAD

**Issue by ernestasjuska** [jimmymcp/al-test-runner#83]
Hi,

Code coverage % is shown when codeunit subtype is _not_ Test.

Test codeunit test procedure does not show code coverage %, but it should:
![image](https://user-images.githubusercontent.com/53167314/223505803-5bc1f2a6-48dc-41c2-ae4c-5a5f522d9d19.png)

Non-test codeunit procedure does show code coverage %, but it shouldn't (it does not matter if I mark that procedure with `[Test]`):
![image](https://user-images.githubusercontent.com/53167314/223506322-12697273-3296-444f-a141-19099dabdbc2.png)

Code coverage % should be shown only for test procedures in test codeunits.

Thanks.

**Comment by jimmymcp** [comment]
The idea is to show the % of lines in production (i.e. non-test) code which are covered by tests. The percentage shows on the production code, not the test code.

See https://jimmymcp.github.io/al-test-runner-docs/articles/code-coverage.html

Cheers

**Comment by ernestasjuska** [comment]
Thank you for clarification.
